//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoaPellido { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string curp { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public int idEstadoOrigen { get; set; }
        public short idEstatus { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual EstatusAlumnos EstatusAlumnos { get; set; }
    }
}
