//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatCursos()
        {
            this.CatCursos1 = new HashSet<CatCursos>();
            this.Cursos = new HashSet<Cursos>();
        }
    
        public short id { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public byte horas { get; set; }
        public Nullable<short> idPreRequisito { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatCursos> CatCursos1 { get; set; }
        public virtual CatCursos CatCursos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos> Cursos { get; set; }
    }
}
